services:
  api:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=ecommercedb;Username=postgres;Password=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - ecommerce-network

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api
    depends_on:
      - api
    networks:
      - ecommerce-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=ecommercedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-data: